name: pfe_2021_juin
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: '^1.3.0'
  path_provider: "^2.0.2"
  rflutter_alert: ^2.0.2
  splash_screen_view: ^3.0.0
  convex_bottom_bar: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: ConcertOne
      fonts:
        - asset: font/ConcertOne-Regular.ttf
